AWSTemplateFormatVersion: "2010-09-09"
Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: "mumbai-keypair"
      DisableApiTermination: false
      ImageId: "ami-0b08bfc6ff7069aff"
      InstanceType: "t3.micro"
      Monitoring: false
      SecurityGroupIds:
        - "sg-07a7396a47e218869"
      Tags:
        - Key: Name
          Value: ec2-explaininstance
  ec2Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: "ap-south-1c"
      Encrypted: false
      Size: 10
      VolumeType: gp3
      Tags:
        - Key: Name
          Value: Ebs-volumes
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private 
      BucketName: "mymainbuckcft"
      Tags:
        - Key: Name
          Value: cloudformations3